#
# Docs
#
# https://docs.aws.amazon.com/AmazonRDS/latest/APIReference/API_CreateDBInstance.html 
# https://docs.aws.amazon.com/AWSCloudFormation/latest/UserGuide/aws-properties-rds-database-instance.html
# https://docs.aws.amazon.com/AWSCloudFormation/latest/UserGuide/quickref-rds.html
# https://docs.aws.amazon.com/AWSCloudFormation/latest/UserGuide/aws-properties-ec2-security-group.html

Parameters:
  AllowedCidrIp:
    Type: String

Resources:
  DBSecurityGroup:
    Type: AWS::EC2::SecurityGroup
    Properties:
      GroupDescription: Allow remote database connections
      SecurityGroupIngress:
      - IpProtocol: tcp
        FromPort: 1433
        ToPort: 1433
        CidrIp: !Ref AllowedCidrIp

  DB1:
    Type: AWS::RDS::DBInstance
    Properties:
      AllocatedStorage: 20
      DBInstanceClass: db.t2.small
      Engine: sqlserver-web
      MasterUsername: MyName
      MasterUserPassword: MyPassword
      PubliclyAccessible: true
      VPCSecurityGroups:
      - !GetAtt DBSecurityGroup.GroupId
