#
# Docs
#
# https://docs.aws.amazon.com/AmazonRDS/latest/APIReference/API_CreateDBInstance.html 
# https://docs.aws.amazon.com/AWSCloudFormation/latest/UserGuide/aws-properties-rds-database-instance.html
# https://docs.aws.amazon.com/AWSCloudFormation/latest/UserGuide/quickref-rds.html

Resources:
  DB1:
    Type: AWS::RDS::DBInstance
    Properties:
      AllocatedStorage: 20
      DBInstanceClass: db.t2.small
      Engine: sqlserver-web
      MasterUsername: MyName
      MasterUserPassword: MyPassword
      PubliclyAccessible: true
